version: '3'
services:
  strapi:
    container_name: strapi-cms
    user: "${UID}:${GID}"
    build: .
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
      - /srv/app/build
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  postgres:
    container_name: strapi-db
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - .pgadmin-data:/var/lib/pgadmin
