version: '3'
services:
  strapi:
    container_name: strapi-cms
    build: .
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
      - /srv/app/build
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  postgres:
    container_name: strapi-db
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.data:/var/lib/postgresql/data